### PR TITLE
added quantum reservoir computing application

### PR DESCRIPTION
**Pull request by fgfuchs**
Added quantum reservoir computing application.

### CODE REVIEW

**Comment by JMuff22** [comment]
Thanks for PR! Please also add changes for the documentations, such as editing the `index.rst` https://github.com/NordIQuEst/application-library/blob/main/hybrid-algorithms/index.rst

**Comment by fgfuchs** [comment]
@JMuff22 I've updated/added indexing files

**Comment by JMuff22** [comment]
@fgfuchs Please add a `requirements.txt` with the dependencies needed to run the notebook. Thanks!

**Comment by fgfuchs** [comment]
> @fgfuchs Please add a `requirements.txt` with the dependencies needed to run the notebook. Thanks!

Thanks @JMuff22, I've added the file.

**Pull request merged**
